#Logging configuration
logging:
  level:
    org.springframework.web: ERROR
    com.doubtnut.backend: DEBUG
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] - [%msg]%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}] - [%msg]%n"
  file: ./doubtnut/logs.log

#Swagger configuration
swagger:
    config:
      base-package: com.doubtnut.backend
      url-endpoints: /api.* 
      application-version: 1.0
      application-name: Doubtnut Backend Assignment App Rest Endpoints
      application-description: Rest End Points for Doubtnut Backend Assignment App
